/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as ModulesRouteImport } from "./routes/modules"
import { Route as IndexRouteImport } from "./routes/index"

const ModulesRoute = ModulesRouteImport.update({
  id: "/modules",
  path: "/modules",
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import("./routes/modules.lazy").then((d) => d.Route))
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import("./routes/index.lazy").then((d) => d.Route))

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/modules": typeof ModulesRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/modules": typeof ModulesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/modules": typeof ModulesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/" | "/modules"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/modules"
  id: "__root__" | "/" | "/modules"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ModulesRoute: typeof ModulesRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/modules": {
      id: "/modules"
      path: "/modules"
      fullPath: "/modules"
      preLoaderRoute: typeof ModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ModulesRoute: ModulesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
